sudo: required
services:
    - docker

before_install:
    - docker build -t guilhermegpg/docker-react -f Dockerfile.dev .

script:
    - docker run guilhermegpg/docker-react npm run test -- --coverage