sudo: required
services:
    - docker

before_install:
    - docker build -t guilhermegpg/docker-react -f Dockerfile.dev .

script:
    - docker run guilhermegpg/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "sa-east-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-sa-east-1-352251318230"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"